# site settings
title: Benjamin Ellenberger
subtitle: , 2022, Data Enthusiast
email: be.ellenberger@gmail.com
description: Data Scientist @ IDSC Insel University Hospital, PhD in the Comp. Neuro. Group of Walter Senn at Uni Bern, personally on Google @bulletphysics @brax and Deep-RL.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Benjamin Ellenberger
street_address:
city:
state: Bern,
zip_code:
country: Switzerland
phone: 01001110 01000001

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/benelot
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/benjamin-ellenberger
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
